### ISSUE TITLE
Can you provide the updated CPF(C-SKY Profiling analysis utils)?

### ISSUE THREAD

**Issue by yelbuod** [XUANTIE-RV/riscv-matrix-extension-spec#10]
CPF is a good profiling analysis tool but it only provided in the package "xuantie-qemu-x86_64-Ubuntu-18.04.tar.gz". Can you provide the source code or executable file of CPF so I can run it on another version of Ubuntu, like Ubuntu 21.04. Thank you!

**Comment by QJtaibai** [comment]
We continually update our tools on the official website; here is the latest link.
https://www.xrvm.cn/community/download?id=4300747789186437120
We regret to inform you that we do not offer an English version of our website. We apologize for any inconvenience caused by the need to use a translation tool to access our pages.

**Comment by yelbuod** [comment]
Thank you for your information!
